#!/bin/sh
#
# apt-howdy -- Check for new available packages
#
# Copyright (C) 2010 Igalia, S.L.
# Authors: Juan A. Suarez Romero <jasuarez@igalia.com>
#
# apt-howdy is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# apt-howdy is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with apt-howdy. If not, see <http://www.gnu.org/licenses/>.
#

BASEDIR=/var/lib/apt-howdy
RSSFILE=${BASEDIR}/new_packages.xml

CACHEDIR=${BASEDIR}/cache
RSSHEADER=${CACHEDIR}/rss-header
FEEDS=${CACHEDIR}/package-feeds
OLDLIST=${CACHEDIR}/package-old-list
NEWLIST=${CACHEDIR}/package-new-list
NEWPACKAGES=${CACHEDIR}/package-news

text_to_html ()
{
	SHORT="s/^\([^ ].*\)$/<p><b>\1<\/b><\/p><p>/"
	PAR="s/^ \.$/<\/p><p>/"
	BREAK="s/^ /<br>/"
	LEAD="s/^ //"

	QUOT="s/\"/\&quot;/g"
	AMP="s/&/\&amp;/g"
	LT="s/</\&lt;/g"
	GT="s/>/\&gt;/g"
	CIRC="s/\^/\&circ;/g"
	TILDE="s/~/\&tilde;/g"
	EURO="s/€/\&euro;/g"

	echo -n "$1</p>" | sed -e "${SHORT};${PAR};${LEAD};${BREAK};${QUOT};${AMP};${LT};${GT};${CIRC};${TILDE};${EURO}"
}

create_rss_header ()
{
	printf "<title>%s</title>\n<link>%s</link>\n<description>%s</description>\n" \
		"New available packages"				\
		"http://igalia.com"					\
		"The list of new available packages after update" >> ${RSSHEADER}
}

initialize ()
{
        if [ ! -d ${BASEDIR} ]; then
                mkdir -p ${BASEDIR}
        fi

        if [ ! -d ${CACHEDIR} ]; then
                mkdir -p ${CACHEDIR}
        fi

	if [ ! -f ${OLDLIST} ]; then
		dpkg-query --showformat '${Package}\n' -W | sort > ${OLDLIST}	
	fi

	if [ ! -f ${RSSHEADER} ]; then
		create_rss_header
	fi

	if [ ! -f ${FEEDS} ]; then
		touch ${FEEDS};
	fi

	if [ ! -f ${RSSFILE} ]; then
		create_rss
	fi
}

get_available_packages ()
{
	dpkg-query --showformat '${Package}\n' -W | sort > ${NEWLIST}
}

compute_new_packages ()
{
	comm ${NEWLIST} ${OLDLIST} -3 > ${NEWPACKAGES}
}

save_new_packages ()
{
	cat ${NEWPACKAGES} >> ${OLDLIST}
	cat ${OLDLIST} | sort > ${OLDLIST}.tmp
	mv ${OLDLIST}.tmp ${OLDLIST}
}

finalize ()
{
	rm ${NEWPACKAGES}
	rm ${NEWLIST}
}

package_to_feed ()
{
	if [ -z $1 ]; then
		return;
	fi

	TITLE=$(dpkg-query -f '${Package}' -W $1)
	DESC=$(dpkg-query -f '${Description}' -W $1)
	DESC1=$(echo -n "${DESC}" | head -n 1)
	DESC2=$(echo -n "${DESC}" | tail -n +2)
	#DESC_HTML=$(text_to_html "<b>${DESC1}</b></p>${DESC2}")
	DESC_HTML=$(text_to_html "$DESC")
	echo "<item><title>${TITLE}</title><description>${DESC_HTML}</description><pubDate>$(date)</pubDate></item>\n" >> ${FEEDS}
}

create_rss ()
{
	printf "<?xml version=\"1.0\"?>\n<rss version=\"2.0\">\n<channel>\n" > ${RSSFILE}
	cat ${RSSHEADER} >> ${RSSFILE}
	cat ${FEEDS} >> ${RSSFILE}
	printf  "</channel>\n</rss>\n" >> ${RSSFILE}
}

# Main program
initialize
get_available_packages
compute_new_packages

if [ ! -s ${NEWPACKAGES} ]; then
	finalize
	return 0
fi

while read PACKAGE ; do
	package_to_feed ${PACKAGE}
done < ${NEWPACKAGES}

save_new_packages
create_rss
finalize
