#!/bin/sh
#
# apt-howdy -- Check for new available packages
#
# Copyright (C) 2010 Igalia, S.L.
# Authors: Juan A. Suarez Romero <jasuarez@igalia.com>
#
# apt-howdy is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# apt-howdy is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with apt-howdy. If not, see <http://www.gnu.org/licenses/>.
#

text_to_html ()
{
	SHORT="s/^\([^ ].*\)$/<p><b>\1<\/b><\/p><p>/"
	PAR="s/^ \.$/<\/p><p>/"
	BREAK="s/^ /<br>/"
	LEAD="s/^ //"

	QUOT="s/\"/\&quot;/g"
	AMP="s/&/\&amp;/g"
	LT="s/</\&lt;/g"
	GT="s/>/\&gt;/g"
	CIRC="s/\^/\&circ;/g"
	TILDE="s/~/\&tilde;/g"
	EURO="s/€/\&euro;/g"

	echo -n "$1</p>" | sed -e "${SHORT};${PAR};${LEAD};${BREAK};${QUOT};${AMP};${LT};${GT};${CIRC};${TILDE};${EURO}"
}

create_rss_header ()
{
	printf "<title>%s</title>\n<link>%s</link>\n<description>%s</description>\n" \
		"New available packages"				\
		"http://igalia.com"					\
		"The list of new available packages after update" >> header
}

initialize ()
{
	if [ ! -f last ]; then
		dpkg-query --showformat '${Package}\n' -W | sort > last	
	fi

	if [ ! -f header ]; then
		create_rss_header
	fi

	if [ ! -f package_feeds ]; then
		touch package_feeds;
	fi

	if [ ! -f new_packages.xml ]; then
		create_rss
	fi
}

get_available_packages ()
{
	dpkg-query --showformat '${Package}\n' -W | sort > available
}

compute_new_packages ()
{
	comm available last -3 > new
}

save_new_packages ()
{
	cat new >> last
	cat last | sort > last.tmp
	mv last.tmp last
}

finalize ()
{
	rm new
	rm available
}

package_to_feed ()
{
	if [ -z $1 ]; then
		return;
	fi

	TITLE=$(dpkg-query -f '${Package}' -W $1)
	DESC=$(dpkg-query -f '${Description}' -W $1)
	DESC1=$(echo -n "${DESC}" | head -n 1)
	DESC2=$(echo -n "${DESC}" | tail -n +2)
	#DESC_HTML=$(text_to_html "<b>${DESC1}</b></p>${DESC2}")
	DESC_HTML=$(text_to_html "$DESC")
	echo "<item><title>${TITLE}</title><description>${DESC_HTML}</description><pubDate>$(date)</pubDate></item>\n" >> package_feeds
}

create_rss ()
{
	printf "<?xml version=\"1.0\"?>\n<rss version=\"2.0\">\n<channel>\n" > new_packages.xml
	cat header >> new_packages.xml
	cat package_feeds >> new_packages.xml
	printf  "</channel>\n</rss>\n" >> new_packages.xml
}

# Main program
initialize
get_available_packages
compute_new_packages

if [ ! -s new ]; then
	finalize
	return 0
fi

while read PACKAGE ; do
	package_to_feed ${PACKAGE}
done < new

save_new_packages
create_rss
finalize
