#!/bin/sh
#
# apt-howdy -- Check for new available packages
#
# Copyright (C) 2010 Igalia, S.L.
# Authors: Juan A. Suarez Romero <jasuarez@igalia.com>
#
# apt-howdy is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# apt-howdy is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with apt-howdy. If not, see <http://www.gnu.org/licenses/>.
#

BASEDIR=/var/lib/apt-howdy		# Place where to put RSS page
CACHEDIR=${BASEDIR}/cache		# Place to put internal files

LASTUPDATE=${CACHEDIR}/last-apt-update	# Contains last time apt was updated
ALARMID=${CACHEDIR}/alarm-id

INTERVAL=120				# Run check every INTERVAL minutes

if [ ! -d ${CACHEDIR} ]; then
	mkdir -p ${CACHEDIR}
fi

if [ "x$1" == "xunregister" ]; then
	if [ -f ${ALARMID} ]; then
		ID=$(<${ALARMID})
		run-standalone.sh dbus-send --session --dest=com.nokia.alarmd --type=method_call /com/nokia/alarmd com.nokia.alarmd.del_event int32:${ID}
		rm ${ALARMID}
	fi
	return 0
fi

if [ "x$1" == "xregister" ]; then
	/usr/lib/apt-howdy-check unregister
	run-standalone.sh dbus-send --session --dest=com.nokia.alarmd --type=method_call --print-reply /com/nokia/alarmd com.nokia.alarmd.add_event objpath:/AlarmdEventRecurring uint32:4 string:action objpath:/AlarmdActionExec uint32:2 string:path string:"/usr/lib/apt-howdy" string:flags int32:17 string:recurr_interval uint32:${INTERVAL} string:recurr_count int32:-1 string:time uint64:$((`date +%s`+10)) | grep int32 | awk '{ print $2 }' > ${ALARMID}
	return 0
fi

if [ ! -f ${LASTUPATE} ]; then
	touch ${LASTUPDATE}
fi

LAST=$(<${LASTUPDATE})
NEW=$(ls -lde /var/lib/apt/lists | cut -c44-67)

if [ "x${LAST}" != "x${NEW}" ]; then
	/usr/lib/apt-howdy
	echo "${NEW}" > ${LASTUPDATE}
fi

