#!/bin/sh

initialize ()
{
	if [ ! -f last_packages ]; then
		touch last_packages
	fi
}

get_available_packages ()
{
	dpkg-query --showformat '${Package}\n' -W | sort
}


# Main program
initialize
get_available_packages


